import { poolSlugFromExternalTeamIdString } from "@/lib/tournament-team-canonical";

/**
 * Fallback conference SEO slugs when `teams.conference` is null (common for bracket-imported rows).
 * Keys are pool `cbbSchoolBySlug` ids from {@link poolSlugFromExternalTeamIdString}.
 * Unmapped slugs aggregate under `other-d1` in analytics.
 */
export const POOL_SLUG_TO_CONFERENCE_SEO: Record<string, string> = {
  // Big 12
  "iowa-state": "big-12",
  kansas: "big-12",
  houston: "big-12",
  "texas-tech": "big-12",
  tcu: "big-12",
  ucf: "big-12",
  byu: "big-12",
  baylor: "big-12",
  "west-virginia": "big-12",
  "oklahoma-state": "big-12",
  "kansas-state": "big-12",
  utah: "big-12",
  colorado: "big-12",
  arizona: "big-12",
  "arizona-state": "big-12",
  cincinnati: "big-12",
  // Big Ten
  purdue: "big-ten",
  illinois: "big-ten",
  michigan: "big-ten",
  "michigan-state": "big-ten",
  "ohio-state": "big-ten",
  indiana: "big-ten",
  wisconsin: "big-ten",
  "penn-state": "big-ten",
  nebraska: "big-ten",
  maryland: "big-ten",
  rutgers: "big-ten",
  northwestern: "big-ten",
  minnesota: "big-ten",
  iowa: "big-ten",
  ucla: "big-ten",
  usc: "big-ten",
  oregon: "big-ten",
  washington: "big-ten",
  // SEC
  alabama: "sec",
  auburn: "sec",
  tennessee: "sec",
  kentucky: "sec",
  florida: "sec",
  georgia: "sec",
  "south-carolina": "sec",
  "texas-am": "sec",
  "ole-miss": "sec",
  "mississippi-state": "sec",
  missouri: "sec",
  arkansas: "sec",
  lsu: "sec",
  vanderbilt: "sec",
  oklahoma: "sec",
  texas: "sec",
  // ACC
  duke: "acc",
  "north-carolina": "acc",
  "nc-state": "acc",
  virginia: "acc",
  "wake-forest": "acc",
  "florida-state": "acc",
  "miami": "acc",
  "virginia-tech": "acc",
  syracuse: "acc",
  clemson: "acc",
  pittsburgh: "acc",
  "georgia-tech": "acc",
  "notre-dame": "acc",
  "boston-college": "acc",
  louisville: "acc",
  stanford: "acc",
  california: "acc",
  smu: "acc",
  // Big East
  uconn: "big-east",
  villanova: "big-east",
  marquette: "big-east",
  creighton: "big-east",
  xavier: "big-east",
  "seton-hall": "big-east",
  providence: "big-east",
  butler: "big-east",
  georgetown: "big-east",
  depaul: "big-east",
  // AAC + MWC + WCC + A-10 + etc.
  memphis: "american",
  "san-diego-state": "mountain-west",
  nevada: "mountain-west",
  "boise-state": "mountain-west",
  unlv: "mountain-west",
  "new-mexico": "mountain-west",
  gonzaga: "west-coast",
  "saint-mary-s": "west-coast",
  "santa-clara": "west-coast",
  "san-francisco": "west-coast",
  dayton: "a-10",
  "saint-louis": "a-10",
  "saint-joseph-s": "a-10",
  davidson: "a-10",
  "george-mason": "a-10",
  richmond: "a-10",
  vcu: "a-10",
  // Often in tournament
  drake: "mvc",
  "loyola-chicago": "mvc",
  "northern-iowa": "mvc",
  "bradley": "mvc",
  "murray-state": "mvc",
  "florida-gulf-coast": "asun",
  liberty: "cusa",
  "grand-canyon": "wac",
  "mcneese": "southland",
  "james-madison": "sun-belt",
  "vermont": "america-east",
  yale: "ivy",
  princeton: "ivy",
  cornell: "ivy",
  harvard: "ivy",
  colgate: "patriot",
  "high-point": "big-south",
  furman: "southern",
  wofford: "southern",
  chattanooga: "southern",
  "oakland": "horizon",
  "wright-state": "horizon",
  akron: "mac",
  "kent-state": "mac",
  "ball-state": "mac",
  "toledo": "mac",
  "ohio-bobcats": "mac",
  howard: "meac",
  "texas-southern": "swac",
  "grambling": "swac",
  "morehead-state": "ovc",
  "north-dakota-state": "summit-league",
  "south-dakota-state": "summit-league",
  "montana-state": "big-sky",
  montana: "big-sky",
  "weber-state": "big-sky",
  "long-beach-state": "big-west",
  "uc-irvine": "big-west",
  "uc-santa-barbara": "big-west",
  "uc-san-diego": "big-west",
  delaware: "caa",
  "unc-wilmington": "caa",
  "college-of-charleston": "caa",
  charleston: "caa",
  "longwood": "big-south",
  "southeast-missouri-state": "ovc",
  "southeast-missouri": "ovc",
  umbc: "america-east",
  "uc-davis": "big-west",
  "north-carolina-central": "meac",
  "norfolk-state": "meac",
  "texas-am-corpus-christi": "southland",
  "texas-aandm-corpus-christi": "southland",
  bryant: "america-east",
  "st-peter-s": "maac",
  "saint-peter-s": "maac",
  iona: "maac",
  manhattan: "maac",
  "fairleigh-dickinson": "northeast",
  "oral-roberts": "summit-league",
  "louisiana": "sun-belt",
  "louisiana-tech": "cusa",
  "north-texas": "american",
  uab: "american",
  "florida-atlantic": "american",
  "south-florida": "american",
  temple: "american",
  tulane: "american",
  "wichita-state": "american"
};

export const OTHER_D1_CONFERENCE_SEO = "other-d1";

export function conferenceSeoSlugForDraftedPlayerTeam(team: {
  conference?: string | null;
  externalTeamId?: string | null;
} | null): string {
  if (!team) return OTHER_D1_CONFERENCE_SEO;
  const fromDb = team.conference?.trim().toLowerCase();
  if (fromDb) return fromDb;
  const slug = poolSlugFromExternalTeamIdString(team.externalTeamId);
  if (!slug) return OTHER_D1_CONFERENCE_SEO;
  return POOL_SLUG_TO_CONFERENCE_SEO[slug] ?? OTHER_D1_CONFERENCE_SEO;
}
